export const GET_NEWS_REQUEST = "GET_NEWS_REQUEST";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAIL = "GET_NEWS_FAIL";

export const GET_TOP_10_NEWS_REQUEST = "GET_TOP_NEWS_REQUEST";
export const GET_TOP_NEWS_REQUEST = "GET_TOP_NEWS_REQUEST";
export const GET_TOP_NEWS_SUCCESS = "GET_TOP_NEWS_SUCCESS";
export const GET_TOP_NEWS_FAIL = "GET_TOP_NEWS_FAIL";

export const CREATE_SINGLE_NEWS_REQUEST = "CREATE_SINGLE_NEWS_REQUEST";
export const CREATE_SINGLE_NEWS_SUCCESS = "CREATE_SINGLE_NEWS_SUCCESS";
export const CREATE_SINGLE_NEWS_FAIL = "CREATE_SINGLE_NEWS_FAIL";

export const UPDATE_SINGLE_NEWS_REQUEST = "UPDATE_SINGLE_NEWS_REQUEST";
export const UPDATE_SINGLE_NEWS_SUCCESS = "UPDATE_SINGLE_NEWS_SUCCESS";
export const UPDATE_SINGLE_NEWS_FAIL = "UPDATE_SINGLE_NEWS_FAIL";

export const DELETE_SINGLE_NEWS_REQUEST = "DELETE_SINGLE_NEWS_REQUEST";
export const DELETE_SINGLE_NEWS_SUCCESS = "DELETE_SINGLE_NEWS_SUCCESS";
export const DELETE_SINGLE_NEWS_FAIL = "DELETE_SINGLE_NEWS_FAIL";

export const CREATE_SINGLE_NEWS_COMMENT_REQUEST = "CREATE_SINGLE_NEWS_COMMENT_REQUEST";
export const CREATE_SINGLE_NEWS_COMMENT_SUCCESS = "CREATE_SINGLE_NEWS_COMMENT_SUCCESS";
export const CREATE_SINGLE_NEWS_COMMENT_FAIL = "CREATE_SINGLE_NEWS_COMMENT_FAIL";

export const DELETE_SINGLE_NEWS_COMMENT_REQUEST = "DELETE_SINGLE_NEWS_COMMENT_REQUEST";
export const DELETE_SINGLE_NEWS_COMMENT_SUCCESS = "DELETE_SINGLE_NEWS_COMMENT_SUCCESS";
export const DELETE_SINGLE_NEWS_COMMENT_FAIL = "DELETE_SINGLE_NEWS_COMMENT_FAIL";

export const CREATE_SINGLE_NEWS_LIKE_REQUEST = "CREATE_SINGLE_NEWS_LIKE_REQUEST";
export const CREATE_SINGLE_NEWS_LIKE_SUCCESS = "CREATE_SINGLE_NEWS_LIKE_SUCCESS";
export const CREATE_SINGLE_NEWS_LIKE_FAIL = "CREATE_SINGLE_NEWS_LIKE_FAIL";

export const DELETE_SINGLE_NEWS_LIKE_REQUEST = "DELETE_SINGLE_NEWS_LIKE_REQUEST";
export const DELETE_SINGLE_NEWS_LIKE_SUCCESS = "DELETE_SINGLE_NEWS_LIKE_SUCCESS";
export const DELETE_SINGLE_NEWS_LIKE_FAIL = "DELETE_SINGLE_NEWS_LIKE_FAIL";

export const GET_USER_NEWS_REQUEST = "GET_USER_NEWS_REQUEST";
export const GET_USER_NEWS_SUCCESS = "GET_USER_NEWS_SUCCESS";
export const GET_USER_NEWS_FAIL = "GET_USER_NEWS_FAIL";

export const ADD_SINGLE_NEWS_TO_USER_REQUEST = "ADD_SINGLE_NEWS_TO_USER_REQUEST";
export const ADD_SINGLE_NEWS_TO_USER_SUCCESS = "ADD_SINGLE_NEWS_TO_USER_SUCCESS";
export const ADD_SINGLE_NEWS_TO_USER_FAIL = "ADD_SINGLE_NEWS_TO_USER_FAIL";

export const DELETE_SINGLE_NEWS_FROM_USER_REQUEST = "DELETE_SINGLE_NEWS_FROM_USER_REQUEST";
export const DELETE_SINGLE_NEWS_FROM_USER_SUCCESS = "DELETE_SINGLE_NEWS_FROM_USER_SUCCESS";
export const DELETE_SINGLE_NEWS_FROM_USER_FAIL = "DELETE_SINGLE_NEWS_FROM_USER_FAIL";

export const CLEAR_NEWS = "CLEAR_NEWS";

export const URL = "/news";
export const USER_URL = "/im/news";
