server:
  context-path: /storage
  port: 8181

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:~/Work/Projects/BSUIR/database/liquid_recipes
    username: root
    password: root
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml

security:
  oauth2:
    resource:
      filter-order: 3

  jwt:
    key: liquidrecipesapplication

  sha:
    length: 256

  resource-servers:
    liquid-recipes:
      id: liquid_recipes_backend

  clients:
    react-app:
      id: liquid_recipes_frontend
      secret: lirefrse
      grant-types: password
      scopes: read, write
      token-action-time: 86400
