export const GET_FLAVORS_REQUEST = "GET_FLAVORS_REQUEST";
export const GET_FLAVORS_SUCCESS = "GET_FLAVORS_SUCCESS";
export const GET_FLAVORS_FAIL = "GET_FLAVORS_FAIL";

export const GET_TOP_10_FLAVORS_REQUEST = "GET_TOP_FLAVORS_REQUEST";
export const GET_TOP_FLAVORS_REQUEST = "GET_TOP_FLAVORS_REQUEST";
export const GET_TOP_FLAVORS_SUCCESS = "GET_TOP_FLAVORS_SUCCESS";
export const GET_TOP_FLAVORS_FAIL = "GET_TOP_FLAVORS_FAIL";

export const CREATE_FLAVOR_REQUEST = "CREATE_FLAVOR_REQUEST";
export const CREATE_FLAVOR_SUCCESS = "CREATE_FLAVOR_SUCCESS";
export const CREATE_FLAVOR_FAIL = "CREATE_FLAVOR_FAIL";

export const UPDATE_FLAVOR_REQUEST = "UPDATE_FLAVOR_REQUEST";
export const UPDATE_FLAVOR_SUCCESS = "UPDATE_FLAVOR_SUCCESS";
export const UPDATE_FLAVOR_FAIL = "UPDATE_FLAVOR_FAIL";

export const DELETE_FLAVOR_REQUEST = "DELETE_FLAVOR_REQUEST";
export const DELETE_FLAVOR_SUCCESS = "DELETE_FLAVOR_SUCCESS";
export const DELETE_FLAVOR_FAIL = "DELETE_FLAVOR_FAIL";

export const CREATE_FLAVOR_COMMENT_REQUEST = "CREATE_FLAVOR_COMMENT_REQUEST";
export const CREATE_FLAVOR_COMMENT_SUCCESS = "CREATE_FLAVOR_COMMENT_SUCCESS";
export const CREATE_FLAVOR_COMMENT_FAIL = "CREATE_FLAVOR_COMMENT_FAIL";

export const DELETE_FLAVOR_COMMENT_REQUEST = "DELETE_FLAVOR_COMMENT_REQUEST";
export const DELETE_FLAVOR_COMMENT_SUCCESS = "DELETE_FLAVOR_COMMENT_SUCCESS";
export const DELETE_FLAVOR_COMMENT_FAIL = "DELETE_FLAVOR_COMMENT_FAIL";

export const CREATE_FLAVOR_LIKE_REQUEST = "CREATE_FLAVOR_LIKE_REQUEST";
export const CREATE_FLAVOR_LIKE_SUCCESS = "CREATE_FLAVOR_LIKE_SUCCESS";
export const CREATE_FLAVOR_LIKE_FAIL = "CREATE_FLAVOR_LIKE_FAIL";

export const DELETE_FLAVOR_LIKE_REQUEST = "DELETE_FLAVOR_LIKE_REQUEST";
export const DELETE_FLAVOR_LIKE_SUCCESS = "DELETE_FLAVOR_LIKE_SUCCESS";
export const DELETE_FLAVOR_LIKE_FAIL = "DELETE_FLAVOR_LIKE_FAIL";

export const GET_USER_FLAVORS_REQUEST = "GET_USER_FLAVORS_REQUEST";
export const GET_USER_FLAVORS_SUCCESS = "GET_USER_FLAVORS_SUCCESS";
export const GET_USER_FLAVORS_FAIL = "GET_USER_FLAVORS_FAIL";

export const ADD_FLAVOR_TO_USER_REQUEST = "ADD_FLAVOR_TO_USER_REQUEST";
export const ADD_FLAVOR_TO_USER_SUCCESS = "ADD_FLAVOR_TO_USER_SUCCESS";
export const ADD_FLAVOR_TO_USER_FAIL = "ADD_FLAVOR_TO_USER_FAIL";

export const DELETE_FLAVOR_FROM_USER_REQUEST = "DELETE_FLAVOR_FROM_USER_REQUEST";
export const DELETE_FLAVOR_FROM_USER_SUCCESS = "DELETE_FLAVOR_FROM_USER_SUCCESS";
export const DELETE_FLAVOR_FROM_USER_FAIL = "DELETE_FLAVOR_FROM_USER_FAIL";

export const CLEAR_FLAVORS = "CLEAR_FLAVORS";

export const URL = "/flavors";
export const USER_URL = "/im/flavors";
