export const GET_RECIPES_REQUEST = "GET_RECIPES_REQUEST";
export const GET_RECIPES_SUCCESS = "GET_RECIPES_SUCCESS";
export const GET_RECIPES_FAIL = "GET_RECIPES_FAIL";

export const GET_TOP_10_RECIPES_REQUEST = "GET_TOP_RECIPES_REQUEST";
export const GET_TOP_RECIPES_REQUEST = "GET_TOP_RECIPES_REQUEST";
export const GET_TOP_RECIPES_SUCCESS = "GET_TOP_RECIPES_SUCCESS";
export const GET_TOP_RECIPES_FAIL = "GET_TOP_RECIPES_FAIL";

export const CREATE_RECIPE_REQUEST = "CREATE_RECIPE_REQUEST";
export const CREATE_RECIPE_SUCCESS = "CREATE_RECIPE_SUCCESS";
export const CREATE_RECIPE_FAIL = "CREATE_RECIPE_FAIL";

export const UPDATE_RECIPE_REQUEST = "UPDATE_RECIPE_REQUEST";
export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS";
export const UPDATE_RECIPE_FAIL = "UPDATE_RECIPE_FAIL";

export const DELETE_RECIPE_REQUEST = "DELETE_RECIPE_REQUEST";
export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS";
export const DELETE_RECIPE_FAIL = "DELETE_RECIPE_FAIL";

export const CREATE_RECIPE_COMMENT_REQUEST = "CREATE_RECIPE_COMMENT_REQUEST";
export const CREATE_RECIPE_COMMENT_SUCCESS = "CREATE_RECIPE_COMMENT_SUCCESS";
export const CREATE_RECIPE_COMMENT_FAIL = "CREATE_RECIPE_COMMENT_FAIL";

export const DELETE_RECIPE_COMMENT_REQUEST = "DELETE_RECIPE_COMMENT_REQUEST";
export const DELETE_RECIPE_COMMENT_SUCCESS = "DELETE_RECIPE_COMMENT_SUCCESS";
export const DELETE_RECIPE_COMMENT_FAIL = "DELETE_RECIPE_COMMENT_FAIL";

export const CREATE_RECIPE_LIKE_REQUEST = "CREATE_RECIPE_LIKE_REQUEST";
export const CREATE_RECIPE_LIKE_SUCCESS = "CREATE_RECIPE_LIKE_SUCCESS";
export const CREATE_RECIPE_LIKE_FAIL = "CREATE_RECIPE_LIKE_FAIL";

export const DELETE_RECIPE_LIKE_REQUEST = "DELETE_RECIPE_LIKE_REQUEST";
export const DELETE_RECIPE_LIKE_SUCCESS = "DELETE_RECIPE_LIKE_SUCCESS";
export const DELETE_RECIPE_LIKE_FAIL = "DELETE_RECIPE_LIKE_FAIL";

export const GET_USER_RECIPES_REQUEST = "GET_USER_RECIPES_REQUEST";
export const GET_USER_RECIPES_SUCCESS = "GET_USER_RECIPES_SUCCESS";
export const GET_USER_RECIPES_FAIL = "GET_USER_RECIPES_FAIL";

export const ADD_RECIPE_TO_USER_REQUEST = "ADD_RECIPE_TO_USER_REQUEST";
export const ADD_RECIPE_TO_USER_SUCCESS = "ADD_RECIPE_TO_USER_SUCCESS";
export const DELETE_RECIPE_FROM_USER_REQUEST = "DELETE_RECIPE_FROM_USER_REQUEST";

export const DELETE_RECIPE_FROM_USER_SUCCESS = "DELETE_RECIPE_FROM_USER_SUCCESS";
export const DELETE_RECIPE_FROM_USER_FAIL = "DELETE_RECIPE_FROM_USER_FAIL";
export const ADD_RECIPE_TO_USER_FAIL = "ADD_RECIPE_TO_USER_FAIL";

export const ADD_ITEM_TO_RECIPE_REQUEST = "ADD_ITEM_TO_RECIPE_REQUEST";
export const ADD_ITEM_TO_RECIPE_SUCCESS = "ADD_ITEM_TO_RECIPE_SUCCESS";
export const ADD_ITEM_TO_RECIPE_FAIL = "ADD_ITEM_TO_RECIPE_FAIL";

export const DELETE_ITEM_FROM_RECIPE_REQUEST = "DELETE_ITEM_FROM_RECIPE_REQUEST";
export const DELETE_ITEM_FROM_RECIPE_SUCCESS = "DELETE_ITEM_FROM_RECIPE_SUCCESS";
export const DELETE_ITEM_FROM_RECIPE_FAIL = "DELETE_ITEM_FROM_RECIPE_FAIL";

export const CLEAR_RECIPES = "CLEAR_RECIPES";

export const URL = "/recipes";
export const USER_URL = "/im/recipes";
